### ISSUE TITLE
Here's a new site I'd like you to consider blocking

### ISSUE THREAD

**Issue by shamindras** [grantwinney/hide-comments-everywhere#166]
Thanks for such a great extension!

Here's a new site I'd like you to consider blocking:

[https://www.crunchyroll.com](https://www.crunchyroll.com)

It's a popular site that is effectively a Netflix for Japanese anime. It would be cool one can only see the anime without the comments.

Typically the comments show in the `https://www.crunchyroll.com/watch/*` url, not the main `https://www.crunchyroll.com` url. This is where the screenings start. For example, here is the [publicly viewable link](https://www.crunchyroll.com/watch/GR3VWXP96/im-luffy-the-man-whos-gonna-be-king-of-the-pirates) to first episode of the anime One Piece. The comments appear at the bottom, even without logging in.

If you could please assist with this, I'd appreciate it.

**Comment by shamindras** [comment]
As a quick update, I found that this works when I manually blacklist the site:

`^www\.crunchyroll\.com; .erc-commenting-section`

Hope this helps!

**Comment by grantwinney** [comment]
You're welcome, and thanks for adding in the selector that works for you.. that makes life easier lol. It's odd though, because I already specify the `commenting-wrapper` element which is slightly higher in the DOM than `.erc-commenting-section`, and when I visit the page you linked to, the extension _does_ hide it. But it won't hurt anything to add the other element too, so I did (5e627e20324e0b8deb67ee61bf2a94eb6a0cea12). Hopefully it works better for you now, after updating the definitions.

**Comment by shamindras** [comment]
Thanks kindly @grantwinney. Not sure why the higher level filter didn't work for me. In either case, all is working well, and nice to know there is an explicit lower level filter on this site.

Appreciate you making the prompt change, and such a useful tool!

**Comment by grantwinney** [comment]
No problem.. take care!
